### ISSUE TITLE
`getPage()` with `feed = TRUE` not returning posts that `feed = FALSE` does

### ISSUE THREAD

**Issue by ctlente** [pablobarbera/Rfacebook#105]
I've been using this package for a couple of days and it is truly amazing, but I encountered a small problem when running `getPage`: not every post returned with `feed = FALSE` also gets returned with `feed = TRUE`.

I was getting the posts from multiple public pages and found this happened with one of them. This was the smallest reproducible example I could manufacture.

```r
# Get posts from page (only from page admin)
posts <- getPage(
  "panvelfarmacias", token, 1000,
  '2017/01/01', '2017/01/31'
  ) %>%
  select(id, from_id, from_name)

# Get posts from page (everyone)
posts_feed <- getPage(
  "panvelfarmacias", token, 1000,
  '2017/01/01', '2017/01/31',
  feed = TRUE) %>%
  select(id, from_id, from_name)

# There shouldn't be any post in 'posts' that is not in 'posts_feed'
setdiff(posts, posts_feed)

#>                               id      from_id        from_name
#> 1 171378594202_10155054433869203 171378594202 Panvel Farmácias
#> 2 171378594202_10155052442979203 171378594202 Panvel Farmácias
#> 3 171378594202_10155049212349203 171378594202 Panvel Farmácias
#> 4 171378594202_10155042263259203 171378594202 Panvel Farmácias
#> 5 171378594202_10155042261309203 171378594202 Panvel Farmácias
#> 6 171378594202_10155033718669203 171378594202 Panvel Farmácias
#> 7 171378594202_10155033689299203 171378594202 Panvel Farmácias
#> 8 171378594202_10155003038309203 171378594202 Panvel Farmácias
```

**Comment by pablobarbera** [comment]
This seems to be an issue with the paging aspect in the API. When I recreate the API calls in these functions, I get the same results through the API explorer as through Rfacebook: [page posts](https://developers.facebook.com/tools/explorer/?method=GET&path=panvelfarmacias%2Fposts%3Ffields%3Dfrom%2Ccreated_time%26limit%3D25%26since%3D2017%2F01%2F01%26until%3D2017%2F01%2F31&version=v2.8) and [page feed](https://developers.facebook.com/tools/explorer/?method=GET&path=panvelfarmacias%2Ffeed%3Ffields%3Dfrom%2Ccreated_time%26limit%3D25%26since%3D2017%2F01%2F01%26until%3D2017%2F01%2F31&version=v2.8). But when I request the limit to be 100 instead of 25, I get more posts on the feed that were not there before: [here](https://developers.facebook.com/tools/explorer/?method=GET&path=panvelfarmacias%2Ffeed%3Ffields%3Dfrom%2Ccreated_time%26limit%3D100%26since%3D2017%2F01%2F01%26until%3D2017%2F01%2F31&version=v2.8).

I'm not sure how to deal with this. I was trying to identify if it's some posts in particular, but there doesn't seem to anything unique about the posts that are not returned by the API. I don't want to change the limit option in the API query, because more than 25 often leads to "too much data" errors. And a quick Google search for this issue with the general API did not return anything relevant.

So.... I'll leave this open for now while I think about it. Thanks for reporting this!
