### ISSUE TITLE
from_name now deprecated

### ISSUE THREAD

**Issue by pooger** [pablobarbera/Rfacebook#168]
https://github.com/pablobarbera/Rfacebook/blob/173257eae1a9e3da23dc771a3ee2da324c9959ac/Rfacebook/R/getCommentReplies.R#L60

As of February 5th Facebook has deprecated the "from" field unless you're using a Page token for the page that user is commenting on: https://developers.facebook.com/docs/graph-api/reference/v2.10/comment 
![image](https://user-images.githubusercontent.com/2415138/35963739-96e4e488-0cad-11e8-8f0a-a5282125bdd3.png)

This throws an "arguments imply differing number of rows: 0, 1" error when repliesToDF is called in Utils: https://github.com/pablobarbera/Rfacebook/blob/master/Rfacebook/R/utils.R#L164

**Comment by pablobarbera** [comment]
Thanks for opening this issue. The function should now return NA for these two fields whenever they are not returned by the API. I also added a note in the documentation to explain this change. (I decided not to remove them altogether to make sure the function is backwards compatible and because some users of the package may still have access through a Page token.)
