### ISSUE TITLE
getInisghts parms argument

### ISSUE THREAD

**Issue by luckiefrenzy** [pablobarbera/Rfacebook#34]
Going through the documentation and trying to pass specific data using parms in getInsights.

Not working. Must be doing something wrong. Would it help to add this as an example in the documentation?

`getInsights(object_id="12345"
                       ,token=token
                       ,parms =c( "&since=2015-05-01T00:00:00%2B0000&until=2015-05-31T00:00:00%2B00000")
                       ,metric='page_stories'
                       ,period = "day")`

**Comment by andrewgeisler** [comment]
@luckiefrenzy 

I did a test based on your example and I received the following error. Is this the same error you received?

> Error in callAPI(url = url, token = token) : 
>  (#100) Must be a unixtime or a date/time representation parseable by strtotime()

Try adjusting the time format in the parms argument as follows:

> parms = "&since=2015-05-01&until=2015-05-31"

Ps. the c() isn't necessary.

I'm doing some further research on how FB accepts time values in the since and until parameters.

**Comment by luckiefrenzy** [comment]
@andrewgeisler 

Yes. That is the exact error. 

The adjustment without the c(), using just date fields worked.

**Comment by andrewgeisler** [comment]
After reading through some web resources (links below), I've come to the conclusion that FB will accept time since/until parameters. However, the %2B was causing the problem. If replaced with a '-' it worked for me. Oddly, replacing with a '+' doesn't work which I didn't expect.

Links:
https://developers.facebook.com/docs/graph-api/using-graph-api/v2.3
http://php.net/manual/en/function.strtotime.php
http://php.net/manual/en/datetime.formats.time.php

@pablobarbera, Would you like me to make updates to any documentation? It's added to the man file but not in the example. Let me know, otherwise I believe this is resolved.

**Comment by pablobarbera** [comment]
@andrewgeisler That would be great! Thanks a lot for looking into this.
