### ISSUE TITLE
admin not getting getInsights()

### ISSUE THREAD

**Issue by tokumotion** [pablobarbera/Rfacebook#39]
Thanks for this wonderful package.

I'm having a little trouble getting data from getInsights() from pages our Business Manager is either admin or owner.

Using this code from a token issued by the BM owner account,

load("/Users/jramirezcastillo/Documents/media_auth")

me <- getInsights(object_id = "227015499643", token = medialab_auth,
            metric = "page_posts_impressions", period = "lifetime")

Which returns:

> me <- getInsights(object_id = "227015499643", token = medialab_auth,
+             metric = "page_posts_impressions", period = "lifetime")
Error in getInsights(object_id = "227015499643", token = medialab_auth,  : 
  No data available. Are you the owner of this page? See ?getInsights.

**Comment by domplexity** [comment]
same here, it's still working in Graph Explorer though. Might try debugging myself, but this will take some time.

**Comment by KeonCummings** [comment]
@domplexity @tokumotion you're getting this error because the metric you are using (page_post_impressions) does not have a lifetime value. If you change the period to day, week, or days_28. It will work. You can check out the api specifics on Facebook. https://developers.facebook.com/docs/graph-api/reference/v2.3/insights

**Comment by domplexity** [comment]
@KeonCummings thanks for the quick reply. the thing is I keep getting this for any getInsights()
tried several pages, although not very active, they should show something in the lifetime period.

````
temp <- getInsights(
  token = fb_oauth,
  object_id = "212430988817198",
  metric = "page_fans",
  period = "lifetime")
```

**Comment by KeonCummings** [comment]
@domplexity have you tried using a temporary token from graph explorer to see if the problem is with your auth token?

**Comment by domplexity** [comment]
@KeonCummings this led me in the right direction: When I created an access token in Graph Explorer associated with the my "R Analytics" App (by default this is set to Graph Explorer, which worked fine, but did not help) I could choose which permissions I (as a user) would like to grant the app. Afterwards it worked with my newly created Rfacebook access token as well. So everything is working now. Thanks alot!

Some questions are remaining, but I'll just post them here in case someone else stumbles over this problem.

1) What do i need to change (presumably in my Facebook App Settings) to get to the dialog box where I specify permissions, when requesting an access token from R?

2) In the aforementioned dialogue Facebook stated, that this I'd need to submit my app to be granted these permissions. However it worked all fine without doing so. Maybe because of dev mode, maybe because I'm also the owner of the app, ...

**Comment by tokumotion** [comment]
Hi, @domplexity!

Thanks for the insight, how did you choose which permissions to give the app in FB Developers?

I cannot find that option to get such options.

Thank you!

**Comment by tokumotion** [comment]
@KeonCummings @domplexity the proceedure you stated should be part of the documentation of the app, IMO. Without giving the app those permissions from the Graph API Explorer you don't get any data from getInsights()

**Comment by pablobarbera** [comment]
@tokumotion @KeonCummings @domplexity If any of you wants to look more into this, and/or edit the documentation, and send a pull request, I would appreciate it! I'm not a page admin, so it's difficult for me to fix this function. Thanks!

**Comment by domplexity** [comment]
@pablobarbera I'll give it a try

**Comment by andrewgeisler** [comment]
@pablobarbera  and @domplexity 

Hey guys - Sorry I'm late to the party. Maybe this will help. 

https://github.com/andrewgeisler/FB_R/blob/master/FB_Authorization.Rmd

There's a way to get a page access token that does not expire. I store it in my .Rprofile config file so I can use it on a continual basis.

**Comment by domplexity** [comment]
@andrewgeisler and @pablobarbera 

I think the problem lay in what you describe in part 2 of your documentation:

> Obtain a short lived access token using developers.facebook.com/tools/explorer.
> Select App (by name)
> Select "all permissions" including extended.

We could already solve this using this workaround. Strange enough there is no way to evoke the permission dialogue when creating the token from R.
