### ISSUE TITLE
getFQL.R with callAPI

### ISSUE THREAD

**Issue by aaronvn** [pablobarbera/Rfacebook#44]
load("fb_oauth")
	d <- getFQL("SELECT uid2 FROM friend WHERE uid1=me()", token=fb_oauth)

getFQL <- function(query, token){
	# cleaning text of query
	query <- gsub(" ", "+", query)
	url <- paste0('https://graph.facebook.com/fql?q=', query)	
	# making query
	content <- callAPI(url=url, token=token)
	
	return(content$data)
}

when i run that program, i have error: it could not find function: "callAPI". thanks a lot. that is the error message.
Error in getFQL("SELECT uid2 FROM friend WHERE uid1=me()", token = fb_oauth) : 
  could not find function "callAPI"

**Comment by pablobarbera** [comment]
@aaronvn I modified the package so that it exports the callAPI function and you can execute as well. I figured other people might find it useful as well. However, my sense is that the error you're getting is probably because FQL queries are not available anymore through the API: https://developers.facebook.com/docs/reference/fql/
