### ISSUE TITLE
Multiple metrics in getInsights

### ISSUE THREAD

**Issue by tokumotion** [pablobarbera/Rfacebook#52]
So I finally found a way to get insights from pages I manage, but I have to make a call for any single metric I want to analyze.

It'd be nice to get a way to pull multiple metrics under one command and also to have a command for pulling all the possible metrics we have available to analyze.

Thank you in advance!

**Comment by andrewgeisler** [comment]
I'm not aware of an end point that can be hit to retrieve a list of available metrics. Sort of a bummer to have to toggle back and forth but they can all be found in FBs documentation. 

Regarding multiple metrics in one call, that could be likely be accomplished using a loop or lapply. That could written in the function itself, but inconsistencies between what periods are available for each metric could cause issues. It's really still making the same amount of calls but the code for the user would be simplified.

**Comment by tokumotion** [comment]
@andrewgeisler Yes, within the function documentation you can state such caveat or provide a list of functions that can be retrieved within the same periods of time.
I've been playing with the function last night and found that `getInsights` work with mostly all the metrics stated [here](https://developers.facebook.com/docs/graph-api/reference/v2.1/insights). 
From Page Video Posts downwards I couldn't get any data.
Also, although this improvement is being worked on on a different issue, error handling needs to tell the user whether the command is wrong or there is not access to make a request to FB API.

**Comment by pablobarbera** [comment]
Just a quick note to encourage anyone interested in these changes to go ahead and make a pull request! I don't have admin access to any page at the moment, so it'd be hard for me to do it myself.

**Comment by andrewgeisler** [comment]
@pablobarbera I can add this to my to do list and take a look at it in the coming days. Are you able to assign it to me so it doesn't fall off my radar?

@tokumotion Since I'm going to working on the function anyways, I'll take a look at the Page Video Posts metrics. I'm going to create a separate issue since that's likely a different problem.

**Comment by pablobarbera** [comment]
@andrewgeisler Thanks! I just added you as collaborator to the repo as well.

**Comment by andrewgeisler** [comment]
@tokumotion 

I'm working on this (sorry for the delay). 
The plan is to let multiple metrics be passed in AS WELL AS multiple periods. If only one period is supplied it will apply to all metrics. This should provide some flexibility.

I think all I really have left to do is to think through how to handle various ways the request might fail (and how to handle it). 

When I get a little further would you be interested in helping me test?

Thanks.

**Comment by tokumotion** [comment]
@andrewgeisler Hi Andrew, yes I'd love to help you with testing.

**Comment by andrewgeisler** [comment]
@tokumotion  The update just got merged in. If you reinstall Rfacebook from github you can give it a go.

I added this to the documentation but it pretty simply. Just pass multiple metrics or periods and you'll get a list of DFs as a result.

Example:
` metric=c('page_fans','page_impressions'), period=c('lifetime','day')`

Keep in mind if there is any conflict between the object type, metric and period, you will get an error.

**Comment by tokumotion** [comment]
@andrewgeisler cool, will test it right away

**Comment by tokumotion** [comment]
@andrewgeisler Check it out and it worked fine. I'm afraid because of the JSON file FB returns, it wouldn't feasible to get the multiple parameters query into a single data frame. Or am I wrong?

**Comment by andrewgeisler** [comment]
@tokumotion I'm glad it worked.

Regarding coercing the results to one data frame:

I'll keep the idea in the back of my mind but I'm a little concerned with building that into the function simply because of the inherit differences in the data that might get returned.

You're right, the results are either 7 cols or 8 cols depending on the metric requested. There is an additional variable column that gets added if the metric has some sort of breakdown. A simple solution might be to insert the metric name as "variable" for the 7 column to get 8 matching columns and then rbind. However, that goes against how I would normal want my data organized. You would end up with a value column with data with a bunch of different meanings. 

From a data organization standpoint I would ideally prefer something *more* like the following:

| end_time  | page_impressions_unique  | page_consumptions_by_consumption_type_unique_video_play  | page_consumptions_by_consumption_type_unique_photo view  |
|---|---|---|---|
| 2015-11-01T07:00:00+0000  | 40 | 2 | 1  |
| 2015-11-02T07:00:00+0000  | 24 | 6 | 1  |

I'm sure it's possible to rewrite how the JSON is parsed to cast the variables to columns, however, you be left wondering what period was used for each metric and that could impact whatever analysis is being performed. I do like how specific the current results are. While some information might seem repetitive, it is very clear what is behind the data since it details what was requested AND the definition of the metric.

Like I said, I'll keep thinking on it. If you'd like, open up another issue with that feature request so it stays on my radar. I'm going to go ahead and close this one.

Thanks.

**Comment by tokumotion** [comment]
@andrewgeisler I guess it can be easier if the JSON can be rewritten into tidy datasets, specially when you get variables with multiple observations per time unit.
Thanks for the changes.
