### ISSUE TITLE
Get the Insights Metric: page_views_external_referrals

### ISSUE THREAD

**Issue by diegocgaona** [pablobarbera/Rfacebook#67]
Hi,

Would be nice if the `getInsights()` could work with the `page_views_external_referrals` metric. 

Today, when I try, I get:

```
teste <- getInsights(object_id = "1522614931338640", token = fb_oauth, metric = c('page_views_external_referrals'), 
                                period = c('day'), parms= paste0("&since=", last_month_s, "&until=", fblast_month_e))

Error in data.frame(unlist(x$data[[1]]$values[[i]]$value), end_time = x$data[[1]]$values[[i]]$end_time,  : 
  arguments imply differing number of rows: 0, 1
```

I think that it is a nice metric to show what sites are important to the fan page.

Thanks!!

**Comment by andrewgeisler** [comment]
@diegocgaona 
Can you try adding the argument version = 2.3 to the request and see if that works?

**Comment by diegocgaona** [comment]
@andrewgeisler , I tried, but the results are the same (I tried other versions too)

```
teste <- getInsights(object_id = "1522614931338640", token = fb_oauth, metric = c('page_views_external_referrals'), 
                     period = c('day'),version = 2.3, parms= paste0("&since=", last_month_s, "&until=", fblast_month_e))
Error in data.frame(unlist(x$data[[1]]$values[[i]]$value), end_time = x$data[[1]]$values[[i]]$end_time,  : 
  arguments imply differing number of rows: 0, 1
```

**Comment by andrewgeisler** [comment]
@diegocgaona  Interesting. I'm not entirely sure what the problem is. The following works just fine for me. I have access to this this particular page (kcId below is a page id) and the token is a long lived token I use continually. I'm also using Rfacebook_0.6.3 which is installed from github not CRAN.  Is the object id you're sending a page id? What happens if you generate a temp token from the API explorer and use that? 

> test <- getInsights(object_id=kcId, token=token, metric=c('page_views_external_referrals'),period=c('day'), parms='&since=2016-03-01&until=2016-03-31',  version = 2.3)

It looks like your error is happening when it tries to parse the response... which means the structure or the response is something that it isn't expecting. That could happen if the credentials are right, or there's a request is bad (metric / period mismatch). All of the arguments look fine to me so barring using an old version of Rfacebook, I'm thinking it may be an object type problem or an authentication issue with the token. Let me know if a temp token works.

**Comment by diegocgaona** [comment]
Hi @andrewgeisler 
Sorry by my stupidity, works with the temporary token. I updated to 0.6.4 too. (I didn't need the version = 2.3 param). And yes, the id is from a page which I'm a admin.

But... it's strange, all the other queries worked fine with my oauth, 
Do you know what can be the error in my permanent token or where I can change it to work?

Many thanks for your help!

**Comment by andrewgeisler** [comment]
@diegocgaona  Sorry for my absence! Did you get this figured out? I don't personally use the oauth method to authenticate so I'm not sure how to help you further. Was your oauth created with extended permissions? Did you try redoing the oauth authentication process?
