### ISSUE TITLE
Error in fromJSON(rawToChar(url.data$content)) 

### ISSUE THREAD

**Issue by RanaivosonHerimanitra** [pablobarbera/Rfacebook#7]
I saw here https://github.com/RanaivosonHerimanitra/Rfacebook/blob/master/Rfacebook/R/searchFacebook.R that one can query a vector of string but when I try : searchFacebook(string=c("world","cup"), token=oauth,n=50)
but also this one:
searchFacebook(string="world cup", token=oauth,n=50)
It always gives me :
Error in fromJSON(rawToChar(url.data$content)) : unexpected character '<'
Or this :searchFacebook(string=c("cup"), token=oauth,n=50)
works fine
Edit:
Same error here:
posts <- searchFacebook(string = "upworthy", token=oauth, n = 500,
since = "25 november 2013 00:00", until = "25 november 2013 23:59")
Error in fromJSON(rawToChar(url.data$content)) : unexpected character '<'

**Comment by VenkatArchitect** [comment]
I'm getting the same error for getPage with the latest RFacebook.

fb_since_date<-"Sat Aug 27 03:33:38 2016"
fb_until_date<-"Sat Aug 27 04:33:38 2016"
fb_oauth <- get_fb_auth()

content<-getPage("fantasyworld", fb_oauth, n = 2000, since=fb_since_date,until=fb_until_date, feed = TRUE, reactions=TRUE)

Error in rjson::fromJSON(rawToChar(url.data$content)) : 
  unexpected character '<'

**Comment by jjcad** [comment]
I'm getting the same error as @VenkatArchitect on Rfacebook v0.6.6 with rjson v0.2.15

**Comment by AmiraBenFaiza** [comment]
HI I HAVE 1 error with Rfacebook:
compositive <- getInsights(object_id='Dental Concept',
                      token = fb_oauth,
                      metric= 'page_positive_feedback_by_type',
                      period =c('day') ,
                      parms='&since=2017-01-01&until=2017-03-03')

Error in rjson::fromJSON(rawToChar(url.data$content)) : 
  unexpected character '<'
