### ISSUE TITLE
Get Insights

### ISSUE THREAD

**Issue by raulmilan** [pablobarbera/Rfacebook#76]
Hi Pablo, thanks for this amazing tool! I love playing with it. Just a minor question:

When I try to get the publicly available page_storytellers_by_country (as apparently page_fans_country does not accept days_28 aggregation and Facebook does not give you daily page_fans for any time back more than 2.5 years) with the getInsights and a copied Token from the GraphAPI with the following code: 

`test = getInsights(object_id="9964154115", token=token, metric="page_storytellers_by_country", period ="days_28", parms='&since=2014-01-01&until=2014-03-01')`

I get the following error message. Which is interesting. Because if I do it in e.g. 2015 it is working...

```
Error in data.frame(unlist(x$data[[1]]$values[[i]]$value), end_time = x$data[[1]]$values[[i]]$end_time,  : 
  arguments imply differing number of rows: 0, 1
```

Any idea what I am doing wrong? Any help is highly appreciated! Many thanks! Raoul

**Comment by andrewgeisler** [comment]
Hey, @raulmilan 

I did some research and while I could not find supporting documentation from FB, I think data is only available two years back. The error you're getting is because the API gives a empty response and that's causing an issue parsing through it. 

I tested this theory on some other metrics (daily) and only got data as far back as 7/24/14. 

If you run this in the API explorer do you get an empty result for the 2014 date range?

@pablobarbera If it's true that data is only available for the prior 2 years, maybe some logic can be added to look at the requested dates and return a "Data unavailable prior to yyyy-MM-dd" message. Just a though.

**Comment by pablobarbera** [comment]
@andrewgeisler PR #81 checks for old data and returns a message. I'll merge it and close this issue once you have had a chance to check it, or if we hear back from @raulmilan . Thanks!!

**Comment by raulmilan** [comment]
@pablobarbera thanks for taking care of this! Your tool is just amazing! @andrewgeisler is totally right. Facebook does not allow extracting page_likes older than 2 years. I tried a lot to get older data, but there is really no way to get the data. In some weird cases I sometimes can also only go back for 18 months. I haven't yet found out, why or when this is the case though. Some industry experts told me that this may be because facebook does not have the information either, but I can't believe this and otherwise they would not have a rolling window of 2 years that is continuously adapting.

**Comment by pablobarbera** [comment]
@raulmilan Interesting! Thanks for chiming in on this :) I added the information message and will close this issue for now.
