### ISSUE TITLE
'post commented date' was earlier than the 'post created date'

### ISSUE THREAD

**Issue by veera0617** [pablobarbera/Rfacebook#78]
Hi pablo,
Thanks for your wonderful Rfacebook package. Its really cool. But i had some problem on this now. 
 
I had retrieved the facebook posts data using getPost(), For some posts, i encountered that the 'post commented date' was earlier than the 'post created date'. When i checked it manually in facebook, i found that there is some problem while retrieving the data.  

For example, the post id "153542981344073_1159481850750176"  data was retrieved through getpost(). It shows that the post created date was "2016-02-22T22:49:56+0000" and the comments created date was  "2016-01-11T16:56:11+0000" "2016-02-02T03:06:12+0000" "2016-01-11T15:17:39+0000" "2016-03-11T01:03:56+0000"  "2016-01-09T17:24:15+0000" "2016-01-13T22:40:24+0000" "2016-01-14T23:01:38+0000" "2016-02-22T23:33:21+0000" "2016-01-25T18:00:39+0000". When the facebook post was created on 2016 february how some one can comment on the post on 2016 january?. 

When i checked the post manually i found that the actual date created was 2016-01-09 10:09am. But the data retrieved from Rfacebook says the post created date was 2016--02-22

To find out the answer i had also posted this issue on this link.
http://stackoverflow.com/questions/37964895/why-facebook-post-date-is-greater-than-the-post-commented-date-in-r

please check it.

some of the post id which had similar problems are
153542981344073_1159481850750176, 153542981344073_1147835821914779, 153542981344073_638451442853222, 153542981344073_456937087671326 and 153542981344073_429242860440749

**Comment by pablobarbera** [comment]
Interesting -- in the first case, it seems the image was reposted on Feb 22, and that's why it shows up in the data as having that date. My guess is that it's the same for the other cases. In any case, it's a problem with the data returned by the API, not Rfacebook, so I'll close this issue for now.

<img width="512" alt="screen shot 2016-06-22 at 2 54 16 pm" src="https://cloud.githubusercontent.com/assets/828570/16267302/59753a52-3889-11e6-8bfc-537f36347951.png">

**Comment by veera0617** [comment]
Agreed Pablo.Thanks for your help. Facebook has to do something for this problem.
